#!/bin/bash

PROJECT_DIR="$PWD"
PROJECT_NAME=TestQA
TEST_ENV=QA
BROWSER=firefox
TIMEOUT_WAIT=30000
TEST_ENV=QA
BASE_URL=https://google.co.in/


HEADLESS=false
SEND_MAIL=false
RECORD_VIDEO=false
PERSISTENT_LOGIN=false
STORE_AUTHENTICATION=false
ENABLE_TRACING=true

DOWNLOAD_PATH=$PROJECT_DIR/output_data/downloads
SCREENSHOT_PATH=$PROJECT_DIR/output_data/screenshots
TRACE_DIR=$PROJECT_DIR/output_data/traces
HAR_PATH=$PROJECT_DIR/output_data/har_path
VIDEO_DIR=$PROJECT_DIR/output_data/videos
PERSISTENT_DIR=$PROJECT_DIR/output_data/dir

cd $PROJECT_DIR || exit

echo Running Test...
echo mvn clean verify -DBROWSER=$BROWSER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DTIMEOUT_WAIT=$TIMEOUT_WAIT -DSEND_MAIL=$SEND_MAIL -DPROJECT_NAME=$PROJECT_NAME -DPROJECT_NAME=$PROJECT_NAME -DBASE_URL=$BASE_URL -DSEND_MAIL=$SEND_MAIL -DDOWNLOAD_PATH=$DOWNLOAD_PATH -DSCREENSHOT_PATH=$SCREENSHOT_PATH -DTRACE_DIR=$TRACE_DIR -DHAR_PATH=$HAR_PATH -DVIDEO_DIR=$VIDEO_DIR -DPERSISTENT_LOGIN=$PERSISTENT_LOGIN -DPERSISTENT_DIR=$PERSISTENT_DIR -DRECORD_VIDEO=$RECORD_VIDEO -DSTORE_AUTHENTICATION=$STORE_AUTHENTICATION -DENABLE_TRACING=$ENABLE_TRACING
mvn clean verify -DBROWSER=$BROWSER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DTIMEOUT_WAIT=$TIMEOUT_WAIT -DSEND_MAIL=$SEND_MAIL -DPROJECT_NAME=$PROJECT_NAME -DPROJECT_NAME=$PROJECT_NAME -DBASE_URL=$BASE_URL -DSEND_MAIL=$SEND_MAIL -DDOWNLOAD_PATH=$DOWNLOAD_PATH -DSCREENSHOT_PATH=$SCREENSHOT_PATH -DTRACE_DIR=$TRACE_DIR -DHAR_PATH=$HAR_PATH -DVIDEO_DIR=$VIDEO_DIR -DPERSISTENT_LOGIN=$PERSISTENT_LOGIN -DPERSISTENT_DIR=$PERSISTENT_DIR -DRECORD_VIDEO=$RECORD_VIDEO -DSTORE_AUTHENTICATION=$STORE_AUTHENTICATION -DENABLE_TRACING=$ENABLE_TRACING

# mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="codegen demo.playwright.dev/todomvc"
# mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="show-trace trace.zip"
# PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
# mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --help"