#!/bin/bash

PROJECT_DIR="$PWD"
DRIVER=firefox
TIMEOUT_WAIT=30000
TEST_ENV=QA
HEADLESS=true
SEND_MAIL=false

cd $PROJECT_DIR

echo Running Test...
echo mvn clean verify -DBROWSER=$DRIVER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DTIMEOUT_WAIT=$EXPLICIT_WAIT -DSEND_MAIL=$SEND_MAIL
mvn clean verify -DBROWSER=$DRIVER -DTEST_ENV=$TEST_ENV -DHEADLESS=$HEADLESS -DTIMEOUT_WAIT=$EXPLICIT_WAIT -DSEND_MAIL=$SEND_MAIL
